# Generated by Django 4.1 on 2022-09-13 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('perfil', models.CharField(max_length=35, verbose_name='Perfil')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('genero', models.CharField(max_length=15, verbose_name='Genero')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=16, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=15, verbose_name='Ciudad')),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sigvitales',
            fields=[
                ('id_signosvitales', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.IntegerField(default=0)),
                ('frecuenciarespiratoria', models.IntegerField(default=0)),
                ('frecuenciacardiaca', models.IntegerField(default=0)),
                ('temperatura', models.IntegerField(default=0)),
                ('glicemias', models.IntegerField(default=0)),
                ('presionarterial', models.IntegerField(default=0)),
                ('fechayhora', models.DateTimeField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signosvitales', to='authApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_salud',
            fields=[
                ('id_pSalud', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=15, verbose_name='Rol')),
                ('especialidad', models.CharField(max_length=20, verbose_name='Especialidad')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pSalud', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_pSalud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='authApp.personal_salud'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.CreateModel(
            name='Hclinica',
            fields=[
                ('id_historiaclinica', models.AutoField(primary_key=True, serialize=False)),
                ('sugerenciacuidado', models.CharField(max_length=200, verbose_name='Sugerenciacuidado')),
                ('diagnostico', models.CharField(max_length=200, verbose_name='Diagnostico')),
                ('entorno', models.CharField(max_length=100, verbose_name='Entorno')),
                ('fechasugerencia', models.DateField()),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiaclinica', to='authApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=15, verbose_name='Parentesco')),
                ('correo', models.EmailField(max_length=15, verbose_name='Correo')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to='authApp.paciente')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
