from .crearpersonalsaludview import CrearPersonalSaludView
from .crearusuarioview import CrearUsuarioView
from .detalleusuarioview import DetalleUsuarioView
from .detallepersonalsaludview import DetallePersonalSaludView